FROM ubuntu:latest

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      g++ \
      git \
      openssh-client \
      python3 \
      python3-dev \
      python3-pip \
      python3-setuptools \
      python3-virtualenv \
      python3-wheel \
      pkg-config

CMD ["python3"]
